name: Commit Message Structure Check

on:
  push:
    branches:
      - '**'

jobs:
  commit_message_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Commit Messages
        run: |
          # Define a regular expression to match the desired commit message structure
          branch_types="feature|bugfix|release|hotfix"
          commit_regex="^($branch_types)\(EAPP-[0-9]+\): .+"

          # Check commit messages using git log without specifying a revision range
          git log --format="%s" | while read -r line; do
            if [[ ! $line =~ $commit_regex ]]; then
              echo "Invalid commit message: $line"
              exit 1  # Exit the script with an error code
            fi
          done
