name: Release to Dev

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!develop'
      - '!release/**'

jobs:
  build:
    name: Build for Development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install
        run: npm ci

      - name: Coverage
        run: npm run test:coverage

      - name: Build
        run: npm run build